services:
  pointcept_me:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - CUDA_ARCH
    image: pointcept_me:pt1.11-cuda11.3
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - ./pcd_files:/workspace/pcd_files
      - ./kpconv_weights/Light_KPFCNN:/workspace/kpconv_weights/Light_KPFCNN
    environment:
      - PYTHONUNBUFFERED=1
    ipc: host
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              count: all